### ISSUE TITLE
An unhandled exception has been thrown: TypeError

### ISSUE THREAD

**Issue by jfl1616** [nextcloud/groupquota#11]
I was able to set the quota for a group via OCC comandline API; however, it throws an below unhandled exception.

root@raspberrypi:/var/www/nextcloud# sudo -u www-data php occ groupquota:set Test 1GB
1073741824
An unhandled exception has been thrown:
TypeError: Return value of "OCA\GroupQuota\Command\SetQuota::execute()" must be of the type int, "null" returned. in /var/www/nextcloud/apps/mail/vendor/symfony/console/Command/Command.php:261
Stack trace:
#0 /var/www/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(920): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(OCA\GroupQuota\Command\SetQuota), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#6 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#7 {main}

**Comment by raise85** [comment]
Same problem too.

This problem occurs from version 20 on. In my case Version 20.0.1
At Version 19.0.4 it works like a charm

**Comment by shibacomputer** [comment]
I have this precise issue, too. Using a fresh Nextcloud 20.0.5 install

**Comment by shibacomputer** [comment]
As an update, this is fixed in 20.0.7

**Comment by icewind1991** [comment]
Should be fixed with 0.1.5
