### ISSUE TITLE
Group not found after renaming (+ How to query with space in group name?)

### ISSUE THREAD

**Issue by Extarys** [nextcloud/groupquota#46]
1. I create a group `Company A`, cannot change the quota because of the space (`_` and `+` as a separator didn't work in the URL). 
2. Renamed `Company A` to `CompanyA` (no space), group not found.
3. Delete `CompanyA`
4. Create again the group `CompanyA` - group found.

```
 curl -u admin:password -H 'OCS-APIRequest: true' https://url.com/apps/groupquota/quota/CompanyA -X POST -d 'quota=200GB'
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>400</statuscode>
  <message>Group not found: CompanyA</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>
```

![image](https://github.com/user-attachments/assets/a22c90ed-96f5-4aa9-bf31-5f4fe7437587)

**Comment by joshtrichards** [comment]
I think the first part is related to how groups are stored internally within `server` (e.g. see nextcloud/server#36840) even once renamed.

As for handling the space, I haven't tested it but these ideas come to mind:

- adding single quotes around the url provided to `curl` - e.g. ` curl -u admin:password -H 'OCS-APIRequest: true' 'https://url.com/apps/groupquota/quota/Company A' -X POST -d 'quota=200GB'
- using `%20`

**Comment by joshtrichards** [comment]
No idea, but tracking it in #9. Feel free to subscribe + upvote.
